version: '3.8'

services:
    php:
        volumes:
            - ./composer.json:/var/www/html/composer.json
            - ./composer.lock:/var/www/html/composer.lock
            - marketplace-admin-data-sync:/var/www/html:nocopy

volumes:
    marketplace-admin-data-sync:
        external: true